apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-bench
spec:
  schedule: "* * * * *"   # run hourly instead of every minute
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          hostPID: true
          nodeSelector:
            kubernetes.io/hostname: sifyadm
          initContainers:
            - name: kube-bench
              image: docker.io/aquasec/kube-bench:v0.11.2
              command:
                - /bin/sh
                - -c
                - |
                  kube-bench --json --outputfile=/results/bench_output.json
              volumeMounts:
                - name: var-lib-cni
                  mountPath: /var/lib/cni
                  readOnly: true
                - mountPath: /var/lib/etcd
                  name: var-lib-etcd
                  readOnly: true
                - mountPath: /var/lib/kubelet
                  name: var-lib-kubelet
                  readOnly: true
                - mountPath: /var/lib/kube-scheduler
                  name: var-lib-kube-scheduler
                  readOnly: true
                - mountPath: /var/lib/kube-controller-manager
                  name: var-lib-kube-controller-manager
                  readOnly: true
                - mountPath: /etc/systemd
                  name: etc-systemd
                  readOnly: true
                - mountPath: /lib/systemd/
                  name: lib-systemd
                  readOnly: true
                - mountPath: /srv/kubernetes/
                  name: srv-kubernetes
                  readOnly: true
                - mountPath: /etc/kubernetes
                  name: etc-kubernetes
                  readOnly: true
                - mountPath: /usr/local/mount-from-host/bin
                  name: usr-bin
                  readOnly: true
                - mountPath: /etc/cni/net.d/
                  name: etc-cni-netd
                  readOnly: true
                - mountPath: /opt/cni/bin/
                  name: opt-cni-bin
                  readOnly: true
                - mountPath: /results
                  name: result-dir
          containers:
            - name: parser
              image: python:3.11
              command: ["sh", "-c"]
              args:
                - |
                  python /scripts/push-metrics.py
              volumeMounts:
                - mountPath: /results
                  name: result-dir
                - mountPath: /scripts
                  name: script-vol
                - mountPath: /var/lib/node_exporter/textfile_collector
                  name: textfile-dir
          volumes:
            - name: var-lib-cni
              hostPath:
                path: /var/lib/cni
            - hostPath:
                path: /var/lib/etcd
              name: var-lib-etcd
            - hostPath:
                path: /var/lib/kubelet
              name: var-lib-kubelet
            - hostPath:
                path: /var/lib/kube-scheduler
              name: var-lib-kube-scheduler
            - hostPath:
                path: /var/lib/kube-controller-manager
              name: var-lib-kube-controller-manager
            - hostPath:
                path: /etc/systemd
              name: etc-systemd
            - hostPath:
                path: /lib/systemd
              name: lib-systemd
            - hostPath:
                path: /srv/kubernetes
              name: srv-kubernetes
            - hostPath:
                path: /etc/kubernetes
              name: etc-kubernetes
            - hostPath:
                path: /usr/bin
              name: usr-bin
            - hostPath:
                path: /etc/cni/net.d/
              name: etc-cni-netd
            - hostPath:
                path: /opt/cni/bin/
              name: opt-cni-bin
            - name: result-dir
              emptyDir: {}
            - name: script-vol
              configMap:
                name: kube-bench-parser
            - name: textfile-dir
              hostPath:
                path: /var/lib/node_exporter/textfile_collector
