prometheus-node-exporter:
  extraArgs:
    - --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
  extraHostVolumeMounts:
    - name: textfile-dir
      hostPath: /var/lib/node_exporter/textfile_collector
      mountPath: /var/lib/node_exporter/textfile_collector
      readOnly: false
