apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway-monitor
  namespace: monitoring
  labels:
    release: monitoring  # This label must match Prometheus's selector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      interval: 15s

